name: Quality Assurance
on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]
  schedule:
    - cron: 0 16 * * *
jobs:

  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: "frontend/node_modules"
          key: node-modules-${{ hashFiles('frontend/package.json') }}
      - name: Install node modules
        run: npm install
        working-directory: ./frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend
      - name: Run unit tests
        run: npm run test
        working-directory: ./frontend
      - name: Bring up containers for e2e testing
        run: docker-compose up -d --build nginx backend celery-worker
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend
